name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install root dependencies
        run: npm ci
      - name: Install function dependencies
        run: npm ci
        working-directory: ./functions
      - name: Install Firebase
        run: curl -sL https://firebase.tools | bash
      - name: Deploy security rules
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
        working-directory: .
      - name: Deploy functions
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
        working-directory: ./functions
